(objective
  "Transform the attached JSON file into a reorganized JSON structure for a book section. The reorganization should focus on conceptual themes, with no content generation required at this stage. Do not generate anything except the JSON structure."  
  "Make sure the section is coherent and logical. The content should be sufficient to answer the questions."
)

(inputs
  (section-json "A JSON file with the section structure.")
  (question-list "A list of questions to be used in the section.")
  (defined-concepts "A list of concepts to that has been generated by the previous sections.")
)

(fields-to-generate
  (field "section_label"
      "A unique label for the section to be used in LaTeX."
  )
  (for-each-subsection
    'Generate and add the following fields to each subsection
    (field "title" "the original title from the input JSON")
    (field "label" "the original label from the input JSON")
    (field "questions" "the original questions from the input JSON")
    (field "concepts" "generate a list of concepts to be explained in the subsection. This is used to keep track of the concepts that have been explained for the future sections. Defined-concepts should not be repeated.")
    (field "prompts"
      "Generate A detailed list of prompts for the LLM chatbot to generate subsection content."
      "Prompts should be elaborated and specific."   
      "Do no explain the defined-concepts and only discuss the concepts that are not defined yet."
    )
    (field "image_prompts"
      "A list of prompts for generating visual content (plots, diagrams, etc.)."
      (image-prompt-fields
        (field "prompt" "Prompt for generating the image that would be helpful for the section, or search phrase for web image.")
        (field "software" "Specify the appropriate software/tool for generating the image (e.g., SVG, gnuplot, Matplotlib, Graphviz, KiCad, Python). or 'web' if the image is better sourced from the web.")
        (field "caption" "Caption for the image, for LaTeX use.")
        (field "label" "Label for the image, for LaTeX use.")        
      )
    )
    (field "table_prompt"
      "A list of prompts for generating LaTeX tables."
      (table-prompt-fields
        (field "prompt" "Prompt for generating the table that would be helpful for the section")
        (field "caption" "Caption for the table, for LaTeX use.")
        (field "label" "Label for the table, for LaTeX use.")
      )
    )
  )
  
)


(deliverable
  "A JSON file with the original section-json augmented with the newly generated fields."
)